### ISSUE TITLE
May I ask the experts how the 【swept】 error is caused?  How to Troubleshooting?

### ISSUE THREAD

**Issue by singdoo** [tobymao/saq#104]
Traceback (most recent call last):
  File "/usr/local/saq-master/examples/del.py", line 95, in <module>
    asyncio.run(enqueue())
  File "/root/anaconda3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/saq-master/examples/del.py", line 89, in enqueue
    result = await queue.apply(batch_delete_url.__name__, uris=uris)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/saq/queue.py", line 580, in apply
    results = await self.map(job_or_func, timeout=timeout, iter_kwargs=[kwargs])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/saq/queue.py", line 670, in map
    raise exc
saq.queue.JobError: Job saq:job:default:3a32d23c-9806-11ee-bd3c-000c29216232 failed

The above job failed with the following error:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.11/site-packages/saq/worker.py", line 260, in process
    result = await asyncio.wait_for(task, job.timeout if job.timeout else None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/asyncio/tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/saq-master/examples/del.py", line 65, in batch_delete_url
    delete_urls = await queue.map(
                  ^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/saq/queue.py", line 670, in map
    raise exc
saq.queue.JobError: Job saq:job:default:3a3341ea-9806-11ee-afa6-000c29216232 aborted

The above job failed with the following error:

swept

**Comment by tobymao** [comment]
maybe it took too long or hung
